export const participantes = [
  "Ana Olivera",
  "Ana Pehar",
  "Alvaro Pedraja",
  "Ana Battagliese",
  "Andrea Pontet",
  "Antonella Batalla",
  "Arianel",
  "Ariel Ramos",
  "Andrea Pontet",
  "Antonio Chamorro",
  "Beatriz Ferrer",
  "Beatriz Abraira",
  "Carlos Monzalvo",
  "Delia Barthe",
  "Delia Luzzo",
  "Eliana Regazzoni",
  "Elsa Muñoz",
  "Estela Roman",
  "Emilio Boné",
  "Federico Segredo",
  "Felix Quintana",
  "Fernando Garcia",
  "Franco De Marco",
  "Gabriela Dobal",
  "Hebe Lasca",
  "Ignacia De Los Santos",
  "Ivonne Tutzo",
  "Jessica Varela",
  "Jorge Cuello",
  "Jorge Rongolino",
  "Jorge Castello",
  "José Batalla",
  "José Alberto Saune",
  "Juan Da Silva",
  "Jorge Spoturno",
  "Leo Uranga",
  "Leonardo Vezzoso",
  "Leticia Lopez",
  "Lucy Mautone",
  "Luis Pehar",
  "Mabel Corrales",
  "Maria Celica",
  "Maria Curci",
  "María Desteffanis",
  "Mariana Lima",
  "Mariela Ortiz",
  "Martin Nuñez",
  "Marisol Mallo",
  "Matilde Garcia",
  "Melina Rongolino",
  "Miguel Bellora",
  "Monica Amado",
  "Moraima Banchero",
  "Nelson Larraud",
  "Paula Motta",
  "Rafael Langelotti",
  "Ricardo Bica",
  "Ricardo Fierro",
  "María Rola Santana",
  "Romina Radeca",
  "Ruben Dario Diaz",
  "Sandra Artigas",
  "Sara Raices",
  "Serrana Batista",
  "Serrana Ibarra",
  "Silvia Delmonte",
  "Susana",
  "Tamara Machain",
  "Teresita Larrea",
  "Teresita Palomeque",
  "Vicente Scópise",
  "Viviana Hirsch",
  "Waldemar Garcia",
];
