export const participantes = [
  "Ana Olivera",
  "Ana",
  "Andrea Pontet",
  "Antonio Chamorro",
  "Beatriz Ferrer",
  "Carlos Monzalvo",
  "Delia Barthe",
  "Emilio Boné",
  "Felix Quintana",
  "Julio Jorge Spoturno",
  "José Batalla",
  "Juan Da Silva",
  "Leo Uranga",
  "Leticia Lopez",
  "Mabel Corrales",
  "Mariana Lima",
  "Mariela Ortiz",
  "Martin Nuñez",
  "Marisol Mallo",
  "Matilde Garcia",
  "Monica Amado",
  "Nelson Larraud",
  "Paula Motta",
  "Ricardo Fierro",
  "Ricardo Bica",
  "Romina Radeca",
  "Sara Raices",
  "Susana",
  "Tamara Machain",
  "Vicente"
];
